### ISSUE TITLE
Release blockers for v0.7.0

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/swtpm#587]
- [X] expiration time of certificates created on the fly should be infinite/as far out in the future as possible? (PR #588)
- [X] expiration time of certificates created for TPM should be infinite/as far out in the future as possible? (PR #588)
- [X] commands inside the VM time out (https://github.com/stefanberger/swtpm/issues/597) (PR #598 )
- [X] Building of RPMs with provided specfile (on recent distros) (PR #601)
- [X] Tested v0.7.0-rc2+ on Fedora 34, CentOS 8, CentOS 9-stream (Oct. , Cygwin, OpenBSD, DragonflyBSD, FreeBSD, Ubuntu 18.04 & 20.04 & 21.04, Fedora 28 PPC64 Big Endian, 
- [X] Do not activate SHA1 PCR bank in swtpm_setup but only SHA256 bank (PR #609)
- [X] Make deamonizing swtpm not racy (PR #612)
- [X] Libvirt discussion needs to resolve (https://listman.redhat.com/archives/libvir-list/2021-November/msg00134.html) and PR #619

**Comment by stefanberger** [comment]
v0.7.0 has been released. closing this issue.
