### ISSUE TITLE
TODO list for v0.10

### ISSUE THREAD

**Issue by stefanberger** [stefanberger/swtpm#877]
- [X] Support for FIPS on the host which restricts available algorithms
  - [X] Disable FIPS mode in OpenSSL instance to be able to run a swtpm instance that requires access to algorithms that are disables by the FIPS mode
  - https://github.com/stefanberger/swtpm/pull/878
- [] If necessary: swtpm_setup.conf: support for more default values not passed on command line to swtpm_setup
- [X] If possible: Updated to latest ibmtss 2 test suite
- [] Add TPM 2 states at different StateFormatLevels filled with data and runs tests
- [X] swtpm to adjust the custom profile considering FIPS enabled host (disables rsaes, camellia, and tdes, and others,  sets ecc-min-size=224 and rsa-min-size=2048); swtpm_setup to use this feature by passing additional command line option
 - [X] Update AppArmor profile
   - run QEMU test: `make check-functional`
